build:
	echo "// DO NOT EDIT THIS FILE. EDIT tabHistoryManager.js main.js INSTEAD" > background.js
	cat tabHistoryManager.js main.js >> background.js
	echo "// DO NOT EDIT THIS FILE. EDIT tabHistoryManager.js main.js INSTEAD" >> background.js

test:	build
	cat tabHistoryManager.js > tabHistoryManagerTestable.js
	echo "module.exports = TabHistoryManager;" >> tabHistoryManagerTestable.js
	npm test tabHistoryManager.test.js
